### ISSUE TITLE
Filter Alert and Event Maps by type and date

### ISSUE THREAD

**Issue by pbiffar** [Terradex/geoserver_new#1]
Steve,
1.) not sure if the ticket should be here, if not please move to correct version

2.) Task: We would like to allow the user to filter out alerts/event by type and time. The log on below (DTSC) shows you why this is useful. We have 1000's of alerts for many years, so it is nearly impossible to find out what happened in the last few days etc.

3.) Here is what we currently have and how it works:

log on to old cleanup deck as sam@terradex.com ruby$1409

You will discover, hidden away and NOT user friendly, obvious a very useful way to filter the results by type and date. See screen shot. 

![2016-02-29_12-23-08](https://cloud.githubusercontent.com/assets/6774165/13407966/fdf9d5b4-dedf-11e5-950a-ff94ea94cec6.png)

Here is how it works ... it is build around one or 2 Views for DTSC alert it is for example 
1.) type: select * from filter_type_landwatch_alert_dtsc_view
2.) time:      -- not sure if it uses this?!? I think dates are hard coded???
         select * from  filter_time_standard_view

The above View(s) are linked to the layer in the tdx_layers table,
Here are the layers which are set up with the filter 
        Select 
        filter_type_view,
        filter_time_view,
        * 
        from tdx_layers
        where NOT filter_type_view is null
        order by layer_name

**Comment by sasignell** [comment]
Are you talking about adding this functionality to landwatch2?

On Mon, Feb 29, 2016 at 3:43 PM, pbiffar <notifications@github.com> wrote:

> Steve,
> 1.) not sure if the ticket should be here, if not please move to correct
> version
>
> 2.) Task: We would like to allow the user to filter out alerts/event by
> type and time. The log on below (DTSC) shows you why this is useful. We
> have 1000's of alerts for many years, so it is nearly impossible to find
> out what happened in the last few days etc.
>
> 3.) Here is what we currently have and how it works:
>
> log on to old cleanup deck as sam@terradex.com ruby$1409
>
> You will discover, hidden away and NOT user friendly, obvious a very
> useful way to filter the results by type and date. See screen shot.
>
> [image: 2016-02-29_12-23-08]
> <https://cloud.githubusercontent.com/assets/6774165/13407966/fdf9d5b4-dedf-11e5-950a-ff94ea94cec6.png>
>
> Here is how it works ... it is build around one or 2 Views for DTSC alert
> it is for example
> 1.) type: select * from filter_type_landwatch_alert_dtsc_view
> 2.) time: -- not sure if it uses this?!? I think dates are hard coded???
> select * from filter_time_standard_view
>
> The above View(s) are linked to the layer in the tdx_layers table,
> Here are the layers which are set up with the filter
> Select
> filter_type_view,
> filter_time_view,
> *
> from tdx_layers
> where NOT filter_type_view is null
> order by layer_name
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Terradex/geoserver_new/issues/1>.
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by pbiffar** [comment]
Steve, any thoughts on this?

**Comment by sasignell** [comment]
I think this is doable-- probably could get it done in 1/2 to 1 day
coding.  It's a bit complicated due to the fact that we're dynamically
drawing in layers for different users, etc.  If this is something you'd
like implemented, lets:
1) move this over to landwatch2 as an issue
2) chat on the phone so I can get a handle on exactly what it is you're
looking for in terms of which layers, users, etc.

On Tue, Mar 15, 2016 at 5:38 PM, pbiffar <notifications@github.com> wrote:

> Steve, any thoughts on this?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Terradex/geoserver_new/issues/1#issuecomment-197032544>
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by pbiffar** [comment]
Moved to Feeder LW2
